# Generated by Django 5.1.1 on 2024-11-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='theme_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
