# Generated by Django 5.1.1 on 2024-11-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('post_name', models.CharField(default='', max_length=100)),
                ('post_date', models.DateField()),
            ],
        ),
    ]
