# Generated by Django 5.1.1 on 2024-11-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
