# Generated by Django 5.1.1 on 2024-11-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_post_name'),
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='theme_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='theme.theme'),
        ),
    ]
