# Generated by Django 5.1.1 on 2024-10-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='message_text',
        ),
    ]
