# Generated by Django 5.1.1 on 2024-10-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_feed', '0002_rename_text_post_message_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='message_text',
            new_name='post_text',
        ),
    ]
