# Generated by Django 5.1.1 on 2024-11-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_feed', '0003_rename_message_text_post_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
